### ISSUE TITLE
statsMultiaddr

### ISSUE THREAD

**Issue by Billou02** [Quilibrium-wiki/YAQAS#2]
hello, after first run of your script, i have edited the config.yml file in ~/quil/.config directory.

the line statsMultiaddr remain empty  
when i read another guides, the line is

statsMultiaddrr: "/dns/stats.quilibrium.com/tcp/443"

Is it a mistake ?
Thanks.

**Comment by krispx2811** [comment]
Yes its a mistake, the script has alot of error atm

**Comment by krispx2811** [comment]
I just relalized to i was mining the past 3 days, and it was all a waste, check your config and apply them manually

**Comment by FireGoblin1337** [comment]
statsMultiaddrr: "/dns/stats.quilibrium.com/tcp/443" is not a requirement for rewards, merely for metrics reporting.
